package org.dizitart.cryptand;

import org.dizitart.cryptand.util.ByteWriter;
import org.dizitart.cryptand.util.U128;
import org.dizitart.cryptand.value.NameDict;
import org.dizitart.cryptand.value.NumType;
import org.dizitart.cryptand.value.Value;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Reads the shared conformance vectors of {@code reference/conformance/vectors}.
 *
 * <p>These vectors are the point. They were generated by the Dart
 * implementation, are consumed unchanged by the Rust one, and now by this — so
 * a disagreement about the bytes shows up here rather than in a customer's file
 * three SDKs later. Nothing in this class reads the Dart or Rust source; it
 * reads JSON and the spec.
 */
final class Vectors {

    private static final ObjectMapper MAPPER = new ObjectMapper();


    private Vectors() {
    }

    static Path root() {
        // The module lives at reference/java; the vectors at reference/conformance/vectors.
        Path p = Path.of("..", "conformance", "vectors").toAbsolutePath().normalize();
        if (!Files.isDirectory(p)) {
            throw new IllegalStateException("conformance vectors not found at " + p);
        }
        return p;
    }

    static JsonNode load(String relative) {
        try {
            return MAPPER.readTree(Files.readAllBytes(root().resolve(relative)));
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    static byte[] hex(String s) {
        return org.dizitart.cryptand.util.Hex.parse(s);
    }

    static String hex(byte[] b) {
        return org.dizitart.cryptand.util.Hex.format(b);
    }

    /** Builds a {@link Value} from the vectors' {@code {"t": ...}} shape. */
    static Value value(JsonNode n) {
        String t = n.get("t").asText();
        switch (t) {
            case "null": return Value.NULL;
            case "bool": return n.get("v").asBoolean() ? Value.TRUE : Value.FALSE;
            case "int": return integer(NumType.byWireName(n.get("w").asText()), new BigInteger(n.get("v").asText()));
            case "float": {
                NumType w = NumType.byWireName(n.get("w").asText());
                byte[] bits = hex(n.get("bits").asText());
                return w == NumType.F32
                        ? new Value.Float(w, Float.intBitsToFloat(beInt(bits)))
                        : new Value.Float(w, Double.longBitsToDouble(beLong(bits)));
            }
            case "str": return new Value.Str(new String(hex(n.get("utf8").asText()), StandardCharsets.UTF_8));
            case "bytes": return new Value.Bytes(hex(n.get("v").asText()));
            case "char": return new Value.Char(n.get("v").asInt());
            case "nitrite_id": return new Value.NitriteId(Long.parseLong(n.get("v").asText()));
            case "uuid": return new Value.Uuid(hex(n.get("v").asText()));
            case "timestamp": return new Value.Timestamp(n.get("millis").asLong());
            case "timestamp_ns": return new Value.TimestampNs(n.get("secs").asLong(), n.get("nanos").asInt());
            case "zoned": return new Value.Zoned(n.get("millis").asLong(), n.get("zone").asText());
            case "date": return new Value.Date(n.get("days").asInt());
            case "time": return new Value.Time(n.get("nanos").asLong());
            case "duration": return new Value.Duration(n.get("secs").asLong(), n.get("nanos").asInt());
            case "regex": return new Value.Regex(n.get("pattern").asText(), n.get("flags").asText());
            case "array": {
                List<Value> items = new ArrayList<>();
                for (JsonNode item : n.get("items")) {
                    items.add(value(item));
                }
                return new Value.Array(items);
            }
            case "map": {
                List<Value.Map.Entry> entries = new ArrayList<>();
                for (JsonNode e : n.get("entries")) {
                    entries.add(new Value.Map.Entry(value(e.get("k")), value(e.get("v"))));
                }
                return new Value.Map(entries);
            }
            case "doc": {
                Map<String, Value> fields = new LinkedHashMap<>();
                JsonNode f = n.get("fields");
                for (Iterator<String> it = f.fieldNames(); it.hasNext(); ) {
                    String name = it.next();
                    fields.put(name, value(f.get(name)));
                }
                return new Value.Doc(fields);
            }
            case "vector": return vector(n);
            case "opaque": return new Value.Opaque(
                    n.get("origin").asText(), n.get("type_name").asText(), hex(n.get("data").asText()));
            case "unknown": return new Value.Unknown(n.get("tag").asInt(), hex(n.get("payload").asText()));
            default: throw new IllegalArgumentException("unhandled vector value type: " + t);
        }
    }

    private static Value vector(JsonNode n) {
        String dtype = n.get("dtype").asText();
        int dim = n.get("dim").asInt();
        ByteWriter w = new ByteWriter();
        switch (dtype) {
            case "f32": {
                for (JsonNode x : n.get("f32")) {
                    w.f32((float) x.asDouble());
                }
                return new Value.Vector(Value.Vector.DTYPE_F32, dim, w.toBytes());
            }
            case "i8": {
                for (JsonNode x : n.get("i8")) {
                    w.u8(x.asInt() & 0xFF);
                }
                w.f32((float) n.get("scale").asDouble());
                w.f32((float) n.get("zero_point").asDouble());
                return new Value.Vector(Value.Vector.DTYPE_I8, dim, w.toBytes());
            }
            default: throw new IllegalArgumentException("unhandled vector dtype: " + dtype);
        }
    }

    /** Splits a signed decimal into the sign-and-magnitude pair {@link Value.Int} holds. */
    static Value.Int integer(NumType type, BigInteger v) {
        boolean negative = v.signum() < 0;
        return new Value.Int(type, negative, U128.fromBigInteger(v.abs()));
    }

    static NameDict dictionary(JsonNode entries) {
        NameDict d = new NameDict();
        for (JsonNode e : entries) {
            d.put(e.get("name_id").asInt(), e.get("name").asText());
        }
        return d;
    }

    private static int beInt(byte[] b) {
        int v = 0;
        for (byte x : b) {
            v = (v << 8) | (x & 0xFF);
        }
        return v;
    }

    private static long beLong(byte[] b) {
        long v = 0;
        for (byte x : b) {
            v = (v << 8) | (x & 0xFF);
        }
        return v;
    }
}
