/// `spec/11-conformance.md` §6 and `spec/14-security.md` §13 — the shared
/// conformance corpus.
///
/// > "Conformance is defined as passing the vectors, not as matching the
/// > reference implementation's source."
///
/// The files live in `reference/conformance/files/` and are generated by
/// `tool/generate_corpus.dart`. Every implementation runs this same list
/// against the same bytes, which is the property the per-implementation
/// negative tests cannot have: each of those builds its own broken file with
/// its own writer and checks that its own reader refuses it, so it can agree
/// with itself and disagree with everyone else. Phase 15 recorded the general
/// shape — "a self-generated vector set cannot contain this fix: the generator
/// and its test both knew they were writing a prefix".
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:cryptand/cryptand.dart';
import 'package:test/test.dart';

const String collectionName = 'orders';
const String nameDictName = 'orders\$names';

Directory get corpusDir {
  // test/ -> cryptand/ -> dart/ -> reference/
  final here = Directory.current.path;
  return Directory('$here/../../conformance/files');
}

Uint8List? unhex(String? s) => s == null
    ? null
    : Uint8List.fromList([
        for (var i = 0; i < s.length; i += 2)
          int.parse(s.substring(i, i + 2), radix: 16)
      ]);

int digest(List<(int, String, Uint8List)> rows) {
  final w = ByteWriter(rows.length * 32);
  for (final (id, country, note) in rows) {
    w.u64(id);
    final c = encodeUtf8Strict(country);
    w
      ..u32(c.length)
      ..bytes(c)
      ..u32(note.length)
      ..bytes(Uint8List.sublistView(note, 0, note.length < 8 ? note.length : 8));
  }
  return crc32c(w.view);
}

/// What one corpus file did to this reader.
final class Result {
  Result(this.findings, this.documents, this.digest);
  Result.failed(this.error) : findings = 0, documents = 0, digest = 0;

  int findings;
  int documents;
  int digest;
  CryptandException? error;
}

/// Opens the file, verifies it, and **reads every document**. All three: §6's
/// `at_open_or_read` exists because some breakages surface only on a read, and
/// a runner that stops at `verify()` reports those as accepted.
Result readFile(String path, Uint8List? key) {
  try {
    final db = DatabaseFile.open(path, key: key);
    // Corruption and tampering only. `spec/01-container.md` section 9: "A leak
    // is repairable" — it is wasted space in a sound file, not damage, and a
    // copy-on-write container leaks tree 1's own pages by one commit as a
    // property of the format (`design/tradeoff-analysis.md` defect 55). A
    // runner that counted leaks would fail every golden file this format can
    // produce.
    final v = db.engine.verifyStructure();
    final r = Result(
        v.of(FindingClass.corruption).length + v.of(FindingClass.tampering).length,
        0,
        0);
    final data = db.catalog.get(collectionName)?.treeId;
    final dictTree = db.catalog.get(nameDictName)?.treeId;
    if (data == null || dictTree == null) {
      throw const CorruptionException('the file does not hold `orders`');
    }
    final names = NameDict();
    final byId = <int, String>{};
    for (final e in db.engine.scanTree(dictTree)) {
      byId[expectValue<CInt>(decodeKey(e.cke), 'name_id').magnitude.lo] =
          expectValue<CStr>(decodeValue(e.value), 'name').value;
    }
    for (final id in byId.keys.toList()..sort()) {
      names.intern(byId[id]!);
    }
    final rows = <(int, String, Uint8List)>[];
    for (final e in db.engine.scanTree(data)) {
      final doc = expectValue<CDoc>(
          decodeValue(e.value, dict: names), 'document');
      rows.add((
        expectValue<CNitriteId>(decodeKey(e.cke), 'document key').id,
        expectField<CStr>(doc, 'country', 'document').value,
        expectField<CBytes>(doc, 'note', 'document').value,
      ));
    }
    rows.sort((a, b) => a.$1.compareTo(b.$1));
    r
      ..documents = rows.length
      ..digest = digest(rows);
    return r;
  } on CryptandException catch (e) {
    return Result.failed(e);
  }
}

/// The class a [CryptandException] belongs to, in the manifest's vocabulary.
String classOf(CryptandException e) => switch (e) {
      TamperException() => 'tampering',
      UnsupportedFeatureException() => 'unsupported',
      CannotUnlockException() => 'tampering',
      _ => 'corruption',
    };

void main() {
  final dir = corpusDir;
  if (!dir.existsSync()) {
    // A missing corpus is a build problem, not a silent pass. §6's suite is
    // mandatory, so a run that skips it must say why rather than go green.
    test('the conformance corpus is present', () {
      fail('${dir.path} does not exist; run '
          '`dart run tool/generate_corpus.dart`');
    });
    return;
  }
  final manifest = jsonDecode(
          File('${dir.path}/manifest.json').readAsStringSync())
      as Map<String, Object?>;
  final files = (manifest['files'] as List).cast<Map<String, Object?>>();

  group('the shared conformance corpus (11 section 6, 14 section 13)', () {
    test('the manifest is not empty and names files that exist', () {
      expect(files, isNotEmpty);
      for (final f in files) {
        expect(File('${dir.path}/${f['name']}').existsSync(), isTrue,
            reason: '${f['name']} is in the manifest and not on disk');
      }
    });

    for (final f in files) {
      final name = f['name'] as String;
      final expectKind = f['expect'] as String;
      final key = unhex(f['key'] as String?);
      final atOpen = f['at_open_or_read'] as bool;
      final tolerated = f['tolerated_clean'] as bool;

      test('$name -- ${f['note']}', () {
        final r = readFile('${dir.path}/$name', key);
        if (expectKind == 'read') {
          expect(r.error, isNull,
              reason: 'a golden file must open: ${r.error}');
          expect(r.findings, 0, reason: 'a golden file must verify clean');
          expect(r.documents, f['documents']);
          expect(r.digest.toRadixString(16).padLeft(8, '0'), f['digest']);
          return;
        }
        // expect == 'error'.
        if (r.error != null) {
          expect(classOf(r.error!), f['error_class'],
              reason: 'the class is what decides whether a repair pass is '
                  'allowed to run over these bytes: ${r.error}');
          return;
        }
        // No exception. §6 permits the verifier to be the one that says so.
        if (r.findings > 0) return;
        if (tolerated) {
          // Conforming, and worth saying out loud: this reader did not exercise
          // the mechanism the file is about.
          printOnFailure('$name was accepted cleanly; tolerated, but the '
              'mechanism it tests did not run');
          return;
        }
        fail('$name was opened, read and verified with nothing reported'
            '${atOpen ? '' : ' (the damage is behind a read, and every '
                'document was read)'}');
      });
    }
  });
}
