//! The conformance vector suite of `11-conformance.md` §7, read by a second
//! implementation. Until this ran, "portable" was a claim: the vectors were
//! generated by the implementation they test, so they caught regression but
//! not misreading.
//!
//! Everything here consumes only JSON and this crate's public encode and
//! decode paths.

#[path = "support_v/mod.rs"]
mod support;

use cryptand::value::{NumType, Value};
use cryptand::{catalog, cke, container, cve, filter, hash, index, security};
use support::{build, hex, load, unhex};

// ---------------------------------------------------------------------------
// cke/values -- spec/03-key-encoding.md
// ---------------------------------------------------------------------------

#[test]
fn cke_cases_encode_to_their_recorded_bytes() {
    let v = load("cke/values");
    for c in v["cases"].as_array().unwrap() {
        let value = build(&c["value"]);
        let got = cke::encode(&value).expect("every case is key-encodable");
        assert_eq!(hex(&got), c["cke"].as_str().unwrap(), "{:?}", value);
    }
}

#[test]
fn cke_cases_decode_back() {
    let v = load("cke/values");
    for c in v["cases"].as_array().unwrap() {
        let bytes = unhex(c["cke"].as_str().unwrap());
        let got = cke::decode_all(&bytes).unwrap_or_else(|e| panic!("{}: {e}", c["cke"]));
        let want = build(&c["value"]);
        // The three lossy decodings of §7 have their own test; here the
        // vector's own case list is round-trippable except for those, which
        // this re-encode check tolerates by comparing bytes, not values.
        let reencoded = cke::encode(&got).unwrap();
        assert_eq!(hex(&reencoded), c["cke"].as_str().unwrap(), "{:?} -> {:?}", want, got);
    }
}

#[test]
fn cke_rejects_are_rejected_and_none_of_them_panics() {
    let v = load("cke/values");
    for r in v["rejects"].as_array().unwrap() {
        let bytes = unhex(r["cke"].as_str().unwrap());
        let got = cke::decode_all(&bytes);
        assert!(got.is_err(), "{} must be rejected: {}", r["cke"], r["why"]);
    }
}

// ---------------------------------------------------------------------------
// numbers/torture -- spec/03-key-encoding.md §4
// ---------------------------------------------------------------------------

#[test]
fn every_torture_entry_encodes_to_its_recorded_bytes() {
    let v = load("numbers/torture");
    let entries = v["entries"].as_array().unwrap();
    assert_eq!(entries.len() as u64, v["count"].as_u64().unwrap());
    for e in entries {
        let value = build(&e["value"]);
        assert_eq!(hex(&cke::encode(&value).unwrap()), e["cke"].as_str().unwrap(), "{value:?}");
    }
}

#[test]
fn the_recorded_sort_order_is_the_byte_order() {
    let v = load("numbers/torture");
    let sorted: Vec<Vec<u8>> =
        v["sorted_by_cke"].as_array().unwrap().iter().map(|s| unhex(s.as_str().unwrap())).collect();
    for i in 1..sorted.len() {
        assert!(sorted[i - 1] <= sorted[i], "entry {i} breaks the recorded order");
    }
    // And the recorded order is the order this implementation produces.
    let mut mine: Vec<Vec<u8>> = v["entries"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| cke::encode(&build(&e["value"])).unwrap())
        .collect();
    mine.sort();
    assert_eq!(mine, sorted, "the sorted vector is not what this encoder produces");
}

/// §1's invariant, in both clauses. The vector states it in prose; this checks
/// it over all 170 x 170 pairs against a logical comparison built without the
/// encoder.
#[test]
fn cke_order_refines_logical_order() {
    let v = load("numbers/torture");
    let vals: Vec<Value> = v["entries"].as_array().unwrap().iter().map(|e| build(&e["value"])).collect();
    let keys: Vec<Vec<u8>> = vals.iter().map(|x| cke::encode(x).unwrap()).collect();
    let mut compared = 0usize;
    for i in 0..vals.len() {
        for j in 0..vals.len() {
            let Some(logical) = logical_cmp(&vals[i], &vals[j]) else { continue };
            compared += 1;
            let bytes = keys[i].cmp(&keys[j]);
            if logical != std::cmp::Ordering::Equal {
                assert_eq!(
                    bytes, logical,
                    "clause 1: {:?} vs {:?} -- memcmp {:?}, logical {:?}",
                    vals[i], vals[j], bytes, logical
                );
            } else {
                // Clause 2: equal values are either the same key, or differ
                // only in the trailing type code, and are therefore adjacent
                // inside [N(v), successor(N(v))).
                let (a, b) = (&keys[i], &keys[j]);
                assert_eq!(a[..a.len() - 1], b[..b.len() - 1], "clause 2: {:?} vs {:?}", vals[i], vals[j]);
                let n = cke::n_of(&vals[i]).unwrap();
                let upper = cke::successor(&n).unwrap();
                assert!(a >= &n && a < &upper, "clause 2: {:?} outside [N(v), successor)", vals[i]);
                assert!(b >= &n && b < &upper, "clause 2: {:?} outside [N(v), successor)", vals[j]);
            }
        }
    }
    assert!(compared > 10_000, "too few comparable pairs to mean anything: {compared}");
}

/// An exact logical comparison (`02-value-encoding.md` §8 rule 2) that does not
/// go through CKE. `None` where an exact comparison would need arbitrary
/// precision -- an integer above 2^53 against a float -- rather than a lossy one.
fn logical_cmp(a: &Value, b: &Value) -> Option<std::cmp::Ordering> {
    use std::cmp::Ordering;
    let as_f = |v: &Value| -> Option<f64> {
        match v {
            Value::Float { v, .. } => Some(*v),
            Value::Int { neg, mag, .. } if *mag <= (1u128 << 53) => {
                Some(if *neg { -(*mag as f64) } else { *mag as f64 })
            }
            _ => None,
        }
    };
    match (a, b) {
        (Value::Int { neg: n1, mag: m1, .. }, Value::Int { neg: n2, mag: m2, .. }) => {
            let sign = |n: &bool, m: &u128| if *m == 0 { 0i32 } else if *n { -1 } else { 1 };
            let (s1, s2) = (sign(n1, m1), sign(n2, m2));
            Some(if s1 != s2 {
                s1.cmp(&s2)
            } else if s1 < 0 {
                m2.cmp(m1)
            } else {
                m1.cmp(m2)
            })
        }
        _ => {
            let (x, y) = (as_f(a)?, as_f(b)?);
            // §8 rule 3: NaN equals NaN and sorts above every other number.
            Some(match (x.is_nan(), y.is_nan()) {
                (true, true) => Ordering::Equal,
                (true, false) => Ordering::Greater,
                (false, true) => Ordering::Less,
                _ => x.partial_cmp(&y).unwrap(),
            })
        }
    }
}

#[test]
fn the_three_lossy_decodings_decode_as_recorded() {
    let v = load("numbers/torture");
    let lossy = v["lossy_decodings"].as_array().unwrap();
    assert_eq!(lossy.len(), 3, "§7 names exactly three lossy cases");
    for l in lossy {
        let got = cke::decode_all(&unhex(l["cke"].as_str().unwrap())).unwrap();
        let want = build(&l["decodes_to"]);
        assert_eq!(got, want, "{}", l["why"]);
    }
}

// ---------------------------------------------------------------------------
// cve/values -- spec/02-value-encoding.md
// ---------------------------------------------------------------------------

#[test]
fn cve_cases_encode_to_their_recorded_bytes() {
    let v = load("cve/values");
    for c in v["cases"].as_array().unwrap() {
        let value = build(&c["value"]);
        assert_eq!(hex(&cve::encode(&value)), c["cve"].as_str().unwrap(), "{value:?}");
    }
}

#[test]
fn cve_cases_round_trip() {
    let v = load("cve/values");
    for c in v["cases"].as_array().unwrap() {
        let bytes = unhex(c["cve"].as_str().unwrap());
        let got = cve::decode_all(&bytes, &|_| None).unwrap_or_else(|e| panic!("{}: {e}", c["cve"]));
        assert_eq!(got, build(&c["value"]), "{}", c["cve"]);
        assert_eq!(hex(&cve::encode(&got)), c["cve"].as_str().unwrap());
    }
}

#[test]
fn cve_rejects_are_rejected() {
    let v = load("cve/values");
    for r in v["rejects"].as_array().unwrap() {
        let bytes = unhex(r["cve"].as_str().unwrap());
        assert!(
            cve::decode_all(&bytes, &|_| None).is_err(),
            "{} must be rejected: {}",
            r["cve"],
            r["why"]
        );
    }
}

// ---------------------------------------------------------------------------
// strings/cases -- spec/00-conventions.md §4, spec/03-key-encoding.md §3.1
// ---------------------------------------------------------------------------

#[test]
fn strings_encode_as_recorded_in_both_encodings() {
    let v = load("strings/cases");
    for c in v["cases"].as_array().unwrap() {
        let s = String::from_utf8(unhex(c["utf8"].as_str().unwrap())).unwrap();
        let value = Value::Str(s.clone());
        assert_eq!(hex(&cke::encode(&value).unwrap()), c["cke"].as_str().unwrap(), "{s:?} CKE");
        assert_eq!(hex(&cve::encode(&value)), c["cve"].as_str().unwrap(), "{s:?} CVE");
    }
}

#[test]
fn nfc_and_nfd_really_are_different_keys() {
    let v = load("strings/cases");
    let find = |utf8: &str| {
        v["cases"]
            .as_array()
            .unwrap()
            .iter()
            .find(|c| c["utf8"] == utf8)
            .map(|c| c["cke"].as_str().unwrap().to_string())
            .unwrap_or_else(|| panic!("{utf8} missing from the vector"))
    };
    assert_ne!(find("c3a9"), find("65cc81"), "the format applies no normalization");
}

#[test]
fn ill_formed_utf8_is_rejected_never_replaced() {
    let v = load("strings/cases");
    for r in v["rejects_on_read"].as_array().unwrap() {
        let raw = unhex(r["utf8"].as_str().unwrap());
        // As a CVE STR payload...
        let mut cve_bytes = vec![0x12, raw.len() as u8];
        cve_bytes.extend_from_slice(&raw);
        assert!(cve::decode_all(&cve_bytes, &|_| None).is_err(), "CVE: {}", r["why"]);
        // ...and as a CKE STRING body.
        let mut key = vec![cke::STRING];
        key.extend_from_slice(&cke::esc(&raw));
        assert!(cke::decode_all(&key).is_err(), "CKE: {}", r["why"]);
    }
    for r in v["rejects_on_write"].as_array().unwrap() {
        // An unpaired surrogate cannot be built as a Rust String at all, which
        // is this language's form of "MUST be rejected on write".
        let utf16 = unhex(r["utf16"].as_str().unwrap());
        let unit = u16::from_be_bytes(utf16.try_into().unwrap());
        assert!(String::from_utf16(&[unit]).is_err(), "{}", r["why"]);
    }
}

// ---------------------------------------------------------------------------
// documents/cases -- spec/02-value-encoding.md §5
// ---------------------------------------------------------------------------

#[test]
fn the_dictionary_reproduces_the_recorded_encoding() {
    let v = load("documents/cases");
    let dict: Vec<(u32, String)> = v["dictionary"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| (e["name_id"].as_u64().unwrap() as u32, e["name"].as_str().unwrap().to_string()))
        .collect();
    let by_name = |n: &str| dict.iter().find(|(_, name)| name == n).map(|(id, _)| *id);
    let by_id = |id: u32| dict.iter().find(|(i, _)| *i == id).map(|(_, n)| n.clone());

    let c = &v["cases"][0];
    let doc = build(&c["value"]);
    let want = c["cve_with_dictionary"].as_str().unwrap();
    assert_eq!(hex(&cve::encode_with_dict(&doc, &by_name)), want);
    assert_eq!(
        hex(&cve::encode(&doc)),
        c["cve_without_dictionary"].as_str().unwrap(),
        "every name inline"
    );

    let back = cve::decode_all(&unhex(want), &by_id).unwrap();
    assert_eq!(back, doc);
    let order: Vec<String> =
        back.as_doc().unwrap().iter().map(|(k, _)| k.clone()).collect();
    let field_order: Vec<String> =
        c["field_order"].as_array().unwrap().iter().map(|x| x.as_str().unwrap().to_string()).collect();
    assert_eq!(order, field_order, "the field table is sorted by resolved name bytes");
}

#[test]
fn reserved_fields_occupy_name_id_1_to_5() {
    let v = load("documents/cases");
    let want = v["reserved_field_ids"].as_object().unwrap();
    // §5.4 names them in this order; the dictionary in the vector must agree.
    let reserved = ["_id", "_revision", "_modified", "_source", "_type"];
    for (i, name) in reserved.iter().enumerate() {
        assert_eq!(want[*name].as_u64().unwrap(), i as u64 + 1, "{name}");
    }
    assert_eq!(want.len(), reserved.len());
}

#[test]
fn an_unknown_tag_inside_an_array_round_trips_byte_for_byte() {
    let v = load("documents/cases");
    let c = &v["cases"][1];
    let bytes = unhex(c["cve"].as_str().unwrap());
    let back = cve::decode_all(&bytes, &|_| None).unwrap();
    assert_eq!(hex(&cve::encode(&back)), c["cve"].as_str().unwrap());
    assert_eq!(back, build(&c["value"]));
}

// ---------------------------------------------------------------------------
// container/layout -- spec/01-container.md §2 and §3
// ---------------------------------------------------------------------------

#[test]
fn the_recorded_superblock_parses_and_matches_its_expectations() {
    let v = load("container/layout");
    let sbv = &v["superblock"];
    let sb = container::Superblock::parse(&unhex(sbv["bytes"].as_str().unwrap())).unwrap();
    let want = &sbv["expected"];
    assert_eq!(sb.vlog_min as u64, want["vlog_min"].as_u64().unwrap());
    assert_eq!(sb.page_size() as u64, want["page_size"].as_u64().unwrap());
    assert_eq!(sb.profile, 1, "the vector says the mobile profile");
    assert_eq!(sb.commit_id, 1);
    assert!(sb.vlog_min as usize <= sb.page_size() / 4, "{}", want["rule"]);
}

#[test]
fn the_recorded_field_offsets_are_the_ones_this_code_uses() {
    let v = load("container/layout");
    let offs = &v["superblock"]["field_offsets"];
    use container::sb;
    for (name, got) in [
        ("magic", sb::MAGIC),
        ("version_major", sb::VERSION_MAJOR),
        ("page_size_log2", sb::PAGE_SIZE_LOG2),
        ("commit_id", sb::COMMIT_ID),
        ("vlog_min", sb::VLOG_MIN),
        ("profile", sb::PROFILE),
        ("next_nonce", sb::NEXT_NONCE),
        ("sb_mac", sb::SB_MAC),
        ("keyslots", sb::KEYSLOTS),
        ("checksum", sb::CHECKSUM),
    ] {
        assert_eq!(offs[name].as_u64().unwrap() as usize, got, "superblock offset of {name}");
    }
}

#[test]
fn the_page_header_is_40_bytes_at_the_recorded_offsets() {
    let v = load("container/layout");
    let phv = &v["page_header"];
    assert_eq!(phv["size"].as_u64().unwrap() as usize, container::PAGE_HEADER_BYTES);
    assert_eq!(container::PAGE_HEADER_BYTES, 40);
    let offs = &phv["field_offsets"];
    use container::ph;
    for (name, got) in [
        ("checksum", ph::CHECKSUM),
        ("page_type", ph::PAGE_TYPE),
        ("flags", ph::FLAGS),
        ("codec_or_reserved", ph::CODEC_OR_RESERVED),
        ("tree_id", ph::TREE_ID),
        ("extent_pages", ph::EXTENT_PAGES),
        ("commit_id", ph::COMMIT_ID),
        ("payload_len", ph::PAYLOAD_LEN),
        ("reserved", ph::RESERVED),
        ("nonce", ph::NONCE),
    ] {
        assert_eq!(offs[name].as_u64().unwrap() as usize, got, "page header offset of {name}");
    }
    let bytes = unhex(phv["bytes"].as_str().unwrap());
    assert_eq!(bytes.len(), 40);
    let h = container::PageHeader::parse(&bytes).unwrap();
    assert_eq!(h.extent_pages, 1);
    assert_eq!(h.commit_id, 1);
}

#[test]
fn the_recorded_crc32c_values_reproduce() {
    let v = load("container/layout");
    for c in v["crc32c"].as_array().unwrap() {
        let input = unhex(c["input"].as_str().unwrap());
        assert_eq!(hash::crc32c(&input) as u64, c["crc"].as_u64().unwrap(), "{}", c["input"]);
    }
}

// ---------------------------------------------------------------------------
// filter/blocked_bloom -- spec/04-segments.md §2.4
// ---------------------------------------------------------------------------

#[test]
fn the_filter_structure_constants_reproduce() {
    let v = load("filter/blocked_bloom");
    let s = &v["structure"];
    assert_eq!(s["block_bits"].as_u64().unwrap() as usize, filter::BLOCK_BITS);
    for (bits, k) in s["probes_for_bits_per_key"].as_object().unwrap() {
        assert_eq!(
            filter::probes_for(bits.parse().unwrap()) as u64,
            k.as_u64().unwrap(),
            "probes at {bits} bits per key"
        );
    }
    let bc = &s["block_count_examples"];
    assert_eq!(bc["32 keys at 16 bits"].as_u64().unwrap(), filter::block_count_for(32, 16));
    assert_eq!(bc["33 keys at 16 bits"].as_u64().unwrap(), filter::block_count_for(33, 16));
    assert_eq!(bc["1000 keys at 16 bits"].as_u64().unwrap(), filter::block_count_for(1000, 16));
}

#[test]
fn the_named_hash_is_cfh64_and_its_vectors_reproduce() {
    let v = load("filter/blocked_bloom");
    assert!(v["hash"].as_str().unwrap().contains("CFH-64"));
    let vectors = v["cfh64_vectors"].as_object().unwrap();
    assert!(vectors.len() >= 6);
    for (key_hex, want) in vectors {
        let got = format!("{:x}", hash::cfh64(&unhex(key_hex)));
        assert_eq!(got, want.as_str().unwrap(), "CFH-64 of {key_hex}");
    }
}

#[test]
fn the_recorded_filter_blocks_reproduce_bit_for_bit() {
    let v = load("filter/blocked_bloom");
    let r = &v["reproduce"];
    let tree_id = r["tree_id"].as_u64().unwrap() as u32;
    let first = r["first_id"].as_i64().unwrap();
    let count = r["key_count"].as_u64().unwrap() as i64;
    let bits = r["bits_per_key"].as_u64().unwrap() as u32;
    let keys: Vec<Vec<u8>> = (0..count)
        .map(|i| {
            let k = cke::encode(&Value::NitriteId(first + i)).unwrap();
            filter::user_key_prefix(tree_id, &k)
        })
        .collect();
    let f = filter::BlockedBloom::build(&keys, bits, keys.len() as u64);
    assert_eq!(hex(&f.blocks), v["blocks"].as_str().unwrap());
    // The whole 20-byte header of §2.4, not a prefix of it: the blocks begin
    // at byte 20, and a reader that assumed 16 would misalign every block.
    let header = v["header_bytes"].as_str().unwrap();
    assert_eq!(header.len() / 2, 20);
    assert_eq!(hex(&f.encode_payload()[..20]), header);
    // A filter's failure mode is a silent false negative, so check there is none.
    assert!(keys.iter().all(|k| f.may_contain(k)));
}

// ---------------------------------------------------------------------------
// security/derivation -- spec/14-security.md §3.3, §3.4, §4.2
// ---------------------------------------------------------------------------

#[test]
fn the_rfc5869_case_reproduces() {
    let v = load("security/derivation");
    let c = &v["hkdf_rfc5869_case1"];
    let got = security::hkdf_sha256(
        &unhex(c["salt"].as_str().unwrap()),
        &unhex(c["ikm"].as_str().unwrap()),
        &unhex(c["info"].as_str().unwrap()),
        c["length"].as_u64().unwrap() as usize,
    );
    assert_eq!(hex(&got), c["okm"].as_str().unwrap());
}

#[test]
fn the_subkeys_reproduce_and_differ_per_purpose() {
    let v = load("security/derivation");
    let s = &v["subkeys"];
    let master = unhex(s["master_key"].as_str().unwrap());
    let uuid: [u8; 16] = unhex(s["database_uuid"].as_str().unwrap()).try_into().unwrap();
    assert_eq!(s["info_prefix"].as_str().unwrap(), security::INFO_PREFIX);
    for purpose in ["page", "vlog", "sbmac"] {
        assert_eq!(
            hex(&security::subkey(&master, &uuid, purpose)),
            s[purpose].as_str().unwrap(),
            "subkey for {purpose}"
        );
    }
    assert_ne!(s["page"], s["vlog"]);
    assert_ne!(s["page"], s["sbmac"]);
}

#[test]
fn the_nonces_reproduce_and_are_24_bytes() {
    let v = load("security/derivation");
    for n in v["nonces"].as_array().unwrap() {
        let built = security::nonce(
            n["domain"].as_u64().unwrap() as u8,
            n["counter"].as_u64().unwrap(),
            n["object_id"].as_u64().unwrap(),
            n["offset"].as_u64().unwrap(),
        )
        .unwrap();
        assert_eq!(built.len(), 24);
        assert_eq!(hex(&built), n["nonce"].as_str().unwrap());
    }
    assert_eq!(
        v["nonce_watermark"]["gap"].as_u64().unwrap(),
        security::NONCE_GAP,
        "§4.1's published floor"
    );
}

#[test]
fn the_keyslot_layout_matches() {
    let v = load("security/derivation");
    let k = &v["keyslot"];
    use security::keyslot as ks;
    assert_eq!(k["size"].as_u64().unwrap() as usize, ks::SIZE);
    assert_eq!(k["count"].as_u64().unwrap() as usize, ks::COUNT);
    assert_eq!(k["offset_in_superblock"].as_u64().unwrap() as usize, ks::OFFSET_IN_SUPERBLOCK);
    assert_eq!(ks::SIZE * ks::COUNT, 576);
    assert_eq!(ks::OFFSET_IN_SUPERBLOCK + ks::SIZE * ks::COUNT, 4088, "keyslots end at the reserved tail");
    let offs = &k["field_offsets"];
    for (name, got) in [
        ("state", ks::STATE),
        ("kdf", ks::KDF),
        ("label_len", ks::LABEL_LEN),
        ("t_cost", ks::T_COST),
        ("m_cost_kib", ks::M_COST_KIB),
        ("parallelism", ks::PARALLELISM),
        ("salt", ks::SALT),
        ("wrap_nonce", ks::WRAP_NONCE),
        ("wrapped_key", ks::WRAPPED_KEY),
        ("wrap_tag", ks::WRAP_TAG),
        ("label", ks::LABEL),
    ] {
        assert_eq!(offs[name].as_u64().unwrap() as usize, got, "keyslot offset of {name}");
    }
}

#[test]
fn the_rfc9106_argon2id_vector_reproduces() {
    let v = load("security/derivation");
    let a = &v["argon2id"];
    let p = &a["params"];
    let (pwd, salt, secret, ad) = (
        unhex(a["password"].as_str().unwrap()),
        unhex(a["salt"].as_str().unwrap()),
        unhex(a["secret"].as_str().unwrap()),
        unhex(a["associated_data"].as_str().unwrap()),
    );
    let (m, t, par, tag_len) = (
        p["memory_kib"].as_u64().unwrap() as u32,
        p["passes"].as_u64().unwrap() as u32,
        p["parallelism"].as_u64().unwrap() as u32,
        p["tag_length"].as_u64().unwrap() as usize,
    );
    let h0 = security::argon2_h0(&pwd, &salt, &secret, &ad, t, m, par, tag_len as u32);
    assert_eq!(hex(&h0), a["h0"].as_str().unwrap(), "RFC 9106 §3.2 step 1");
    let tag = security::argon2id(&pwd, &salt, &secret, &ad, t, m, par, tag_len).unwrap();
    assert_eq!(hex(&tag), a["tag"].as_str().unwrap());
    assert_eq!(a["version"].as_u64().unwrap(), 0x13);
}

#[test]
fn the_profile_costs_are_at_or_above_the_writer_floor() {
    let v = load("security/derivation");
    let c = &v["profile_costs"];
    let floor = &c["writer_floor"];
    let (ft, fm, fp) = (
        floor["t_cost"].as_u64().unwrap(),
        floor["m_cost_kib"].as_u64().unwrap(),
        floor["parallelism"].as_u64().unwrap(),
    );
    for profile in ["mobile", "tablet", "desktop", "server"] {
        let p = &c[profile];
        assert!(p["t_cost"].as_u64().unwrap() >= ft, "{profile} t_cost");
        assert!(p["m_cost_kib"].as_u64().unwrap() >= fm, "{profile} m_cost");
        assert!(p["parallelism"].as_u64().unwrap() >= fp, "{profile} parallelism");
    }
}

#[test]
fn nothing_in_security_section_2_is_undeclared_or_absent() {
    let v = load("security/derivation");
    assert!(v["not_implemented"].as_array().unwrap().is_empty());
    assert!(!v["argon2id"].is_null());
    assert!(!v["hkdf_rfc5869_case1"].is_null());
}

// ---------------------------------------------------------------------------
// index -- spec/06-indexes.md
// ---------------------------------------------------------------------------

#[test]
fn every_index_entry_key_reproduces() {
    let v = load("index/layout");
    for e in v["entries"].as_array().unwrap() {
        let value = build(&e["indexed_value"]);
        let id = e["nitrite_id"].as_i64().unwrap();
        let key = cke::encode(&Value::Array(vec![value.clone(), Value::NitriteId(id)])).unwrap();
        assert_eq!(hex(&key), e["key"].as_str().unwrap(), "{value:?}");
    }
}

#[test]
fn eq_5_across_numeric_types_contains_every_recorded_member() {
    let v = load("index/layout");
    let eq = &v["range_construction"]["eq_5_any_numeric_type"];
    let lower = cke::n_of(&Value::int(NumType::I32, 5)).unwrap();
    let upper = cke::successor(&lower).unwrap();
    assert_eq!(hex(&lower), eq["lower"].as_str().unwrap());
    assert_eq!(hex(&upper), eq["upper"].as_str().unwrap());
    for k in eq["contains"].as_array().unwrap() {
        let key = unhex(k.as_str().unwrap());
        assert!(key >= lower && key < upper, "{k} is outside [N(5), successor(N(5)))");
    }
    // The point of §8.2: the same bound built from CKE(v) would not.
    let wrong = cke::encode(&Value::int(NumType::I32, 5)).unwrap();
    assert!(
        eq["contains"].as_array().unwrap().iter().any(|k| unhex(k.as_str().unwrap()) < wrong),
        "a CKE(v) bound would cut inside the equality class"
    );
}

#[test]
fn the_recorded_range_helpers_reproduce() {
    let v = load("index/layout");
    let rc = &v["range_construction"];
    assert_eq!(
        hex(&cke::array_prefix_numeric(&[Value::int(NumType::I32, 5)]).unwrap()),
        rc["array_prefix_numeric_5"].as_str().unwrap()
    );
    let sw = &rc["starts_with_abc"];
    let mut lower = vec![cke::STRING];
    lower.extend_from_slice(&cke::esc_open(b"abc"));
    assert_eq!(hex(&lower), sw["lower"].as_str().unwrap());
    assert_eq!(hex(&cke::successor(&lower).unwrap()), sw["upper"].as_str().unwrap());
}

#[test]
fn every_index_entry_case_reproduces_its_keys_byte_for_byte() {
    let v = load("index/entries");
    for c in v["cases"].as_array().unwrap() {
        let fields: Vec<String> =
            c["fields"].as_array().unwrap().iter().map(|f| f.as_str().unwrap().to_string()).collect();
        let doc = build(&c["document"]);
        let id = match build(&c["nitrite_id"]) {
            Value::NitriteId(i) => i,
            other => panic!("expected a NitriteId, got {other:?}"),
        };
        let got: Vec<String> =
            index::index_keys(&doc, &fields, c["sparse"].as_bool().unwrap(), id)
                .unwrap()
                .iter()
                .map(|k| hex(k))
                .collect();
        let want: Vec<String> =
            c["keys"].as_array().unwrap().iter().map(|k| k.as_str().unwrap().to_string()).collect();
        assert_eq!(got, want, "{}", c["note"]);
    }
}

#[test]
fn the_cap_and_the_field_path_escapes_are_what_the_vector_says() {
    let v = load("index/entries");
    assert_eq!(v["cap_per_document"].as_u64().unwrap() as usize, index::CAP_PER_DOCUMENT);
    for (path, want) in v["field_path_escapes"].as_object().unwrap() {
        if path == "note" {
            continue;
        }
        let want: Vec<String> =
            want.as_array().unwrap().iter().map(|x| x.as_str().unwrap().to_string()).collect();
        assert_eq!(index::parse_field_path(path), want, "{path}");
    }
}

// ---------------------------------------------------------------------------
// catalog/trees -- spec/05-catalog.md
// ---------------------------------------------------------------------------

#[test]
fn reserved_tree_ids_match_the_vector() {
    let v = load("catalog/trees");
    let ids = &v["reserved_tree_ids"];
    use catalog::tree_id as t;
    for (name, got) in [
        ("catalog", t::CATALOG),
        ("free_space", t::FREE_SPACE),
        ("attributes", t::ATTRIBUTES),
        ("tree_index", t::TREE_INDEX),
        ("repair_log", t::REPAIR_LOG),
        ("users", t::USERS),
        ("manifest", t::MANIFEST),
        ("vlog_stats", t::VLOG_STATS),
        ("checkpoints", t::CHECKPOINTS),
        ("change_feed", t::CHANGE_FEED),
        ("first_user_tree", t::FIRST_USER_TREE),
    ] {
        assert_eq!(ids[name].as_u64().unwrap() as u32, got, "tree id of {name}");
    }
}

#[test]
fn the_five_portable_index_type_names_are_exactly_these() {
    let v = load("catalog/trees");
    let want: Vec<&str> = v["index_type_names"]["values"]
        .as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_str().unwrap())
        .collect();
    let mut mine = catalog::PORTABLE_INDEX_TYPES.to_vec();
    mine.sort();
    assert_eq!(mine, want);
}

#[test]
fn levelled_kinds_match_the_vector() {
    let v = load("catalog/trees");
    let want: Vec<&str> =
        v["levelled_kinds"].as_array().unwrap().iter().map(|x| x.as_str().unwrap()).collect();
    let mut mine = catalog::LEVELLED_KINDS.to_vec();
    mine.sort();
    assert_eq!(mine, want);
}

#[test]
fn a_descriptor_re_encodes_to_the_same_bytes() {
    let v = load("catalog/trees");
    for t in v["trees"].as_array().unwrap() {
        let name = t["name"].as_str().unwrap();
        assert_eq!(
            hex(&cke::encode(&Value::Str(name.to_string())).unwrap()),
            t["name_key"].as_str().unwrap(),
            "the catalog key of {name}"
        );
        let want = t["descriptor_without_created"].as_str().unwrap();
        let d = cve::decode_all(&unhex(want), &|_| None)
            .unwrap_or_else(|e| panic!("{name}: {e}"));
        match d.field("tree_id") {
            Some(Value::Int { mag, .. }) => {
                assert_eq!(*mag as u64, t["tree_id"].as_u64().unwrap(), "{name}")
            }
            other => panic!("{name}: tree_id is {other:?}"),
        }
        assert_eq!(d.field("kind"), Some(&Value::Str(t["kind"].as_str().unwrap().to_string())));
        assert_eq!(d.field("levelled"), Some(&Value::Bool(t["levelled"].as_bool().unwrap())));
        assert_eq!(hex(&cve::encode(&d)), want, "{name} must round-trip byte for byte");
    }
}

#[test]
fn the_store_metadata_key_is_a_cke_string() {
    let v = load("catalog/trees");
    let key = cke::encode(&Value::Str("$store".to_string())).unwrap();
    assert_eq!(hex(&key), v["store_metadata_key"].as_str().unwrap());
}

/// Not a vector: a key whose ordering region is fractional but whose type code
/// says integer. `03-key-encoding.md` §7's reject list does not mention it, so
/// two conforming decoders may disagree; this one refuses rather than truncate.
#[test]
fn an_integer_type_code_over_a_fractional_region_is_refused() {
    // sign positive, e = 0, mantissa 0xC0 -> 1.5, type code 0x02 (I32).
    let key = unhex("30034000c0000002");
    assert!(cke::decode_all(&key).is_err());
    // The same bytes with an F64 type code are a perfectly good 1.5.
    let f = cke::decode_all(&unhex("30034000c000000b")).unwrap();
    assert_eq!(f, Value::Float { w: NumType::F64, v: 1.5 });
}
