//! A second, independent implementation of the Cryptand file format's byte
//! layer, written from `spec/` and checked against the conformance vectors in
//! `reference/conformance/vectors`.
//!
//! It exists for one reason: the vectors were generated by the Dart reference
//! implementation, so until a second implementation reads them they catch
//! regression but not misreading (`REPORT.md` §6). This crate is the reader.
//! It deliberately does not implement the engine — only what
//! `11-conformance.md` §7 defines conformance as: the vectors.

pub mod catalog;
pub mod cke;
pub mod container;
pub mod cve;
pub mod filter;
pub mod hash;
pub mod index;
pub mod security;
pub mod value;
pub mod varint;

/// `00-conventions.md` §9 keeps corruption and tampering apart; nothing in this
/// crate reaches the tampering case, so one variant carrying a reason is enough.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Corrupt(pub String);

impl std::fmt::Display for Corrupt {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "corrupt: {}", self.0)
    }
}

impl std::error::Error for Corrupt {}

pub type Result<T> = std::result::Result<T, Corrupt>;

pub fn corrupt<T>(why: impl Into<String>) -> Result<T> {
    Err(Corrupt(why.into()))
}
